CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created_at TIMESTAMP NOT NULL,
    display_name TEXT,
    token_hash TEXT,
    is_private BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    player_count INT NOT NULL DEFAULT 0,
    moves_played JSONB NOT NULL DEFAULT '{}'::jsonb,
    ended_at TIMESTAMP
);

CREATE UNIQUE INDEX uc_token_hash ON rooms (token_hash)
WHERE
    token_hash IS NOT NULL
    AND is_active = TRUE;

CREATE INDEX idx_rooms_listing ON rooms (player_count DESC)
WHERE
    is_active = TRUE;

CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    room_id BIGINT NOT NULL REFERENCES rooms (id),
    session_hash TEXT NOT NULL,
    joined_at TIMESTAMP NOT NULL,
    left_at TIMESTAMP,
    display_name VARCHAR(50),
    is_winner BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_players_in_game ON players (room_id);

CREATE UNIQUE INDEX uc_one_session_per_game ON players (room_id, session_hash);

CREATE UNIQUE INDEX uc_one_display_name_per_game ON players (room_id, display_name);

CREATE UNIQUE INDEX uc_one_winner_per_game ON players (room_id)
WHERE
    is_winner = TRUE;