CREATE TABLE rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    invite_code_hash TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    ended_at TIMESTAMP,
    player_count INT NOT NULL DEFAULT 0,
    game_state JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX uc_room_invite_code_hash ON rooms (invite_code_hash)
WHERE active = TRUE;

CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    room_id BIGINT NOT NULL REFERENCES rooms (id),
    ref_no BIGINT NOT NULL,
    joined_at TIMESTAMP NOT NULL,
    disconnected_at TIMESTAMP,
    display_name VARCHAR(50),
    winner BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE SEQUENCE players_ref_no_seq;

CREATE INDEX idx_players_in_room ON players (room_id);

CREATE UNIQUE INDEX uc_player_ref_no_per_room ON players(room_id, ref_no);

CREATE UNIQUE INDEX uc_player_one_winner_per_room ON players (room_id)
WHERE
    winner = TRUE;

CREATE TABLE refresh_tokens (
    session_hash TEXT NOT NULL,
    token_hash TEXT NOT NULL,
    room_id BIGINT NOT NULL REFERENCES rooms(id),
    player_id BIGINT NOT NULL REFERENCES players(id),
    issued_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    revoked_at TIMESTAMP
);

CREATE INDEX idx_refresh_tokens_by_session ON refresh_tokens(session_hash)
WHERE revoked = FALSE;

CREATE UNIQUE INDEX uc_refresh_tokens_token_hash ON refresh_tokens(token_hash)
WHERE revoked = FALSE;

CREATE INDEX idx_refresh_tokens_active_token ON refresh_tokens(token_hash, expires_at)
WHERE revoked = FALSE;